"""Add StressIndex and MarketData models

Revision ID: 016de952e744
Revises: 8bd1ad8b982e
Create Date: 2026-02-01 19:42:28.992444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016de952e744'
down_revision: Union[str, Sequence[str], None] = '8bd1ad8b982e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Ticker symbol: SPY, ^GSPC, ^DJI, ^VIX, etc.'),
    sa.Column('asset_type', sa.String(length=20), nullable=False, comment='Asset type: index, stock, etf, crypto, commodity, forex'),
    sa.Column('exchange', sa.String(length=20), nullable=True, comment='Exchange: NYSE, NASDAQ, LSE, TYO, etc.'),
    sa.Column('region', sa.String(length=10), nullable=True, comment='Region: us, eu, uk, jp, cn, etc.'),
    sa.Column('date', sa.Date(), nullable=False, comment='Trading date'),
    sa.Column('open', sa.Float(), nullable=True, comment='Opening price'),
    sa.Column('high', sa.Float(), nullable=True, comment='High price'),
    sa.Column('low', sa.Float(), nullable=True, comment='Low price'),
    sa.Column('close', sa.Float(), nullable=False, comment='Closing price'),
    sa.Column('adj_close', sa.Float(), nullable=True, comment='Adjusted closing price (for splits/dividends)'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='Trading volume'),
    sa.Column('daily_return', sa.Float(), nullable=True, comment='Daily return (close-to-close)'),
    sa.Column('volatility', sa.Float(), nullable=True, comment='Realized volatility (rolling window)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Data source: covid_indices, yahoo, tiingo, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_data_symbol_date')
    )
    op.create_index('ix_market_data_asset_type', 'market_data', ['asset_type'], unique=False)
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index('ix_market_data_source', 'market_data', ['source'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_symbol_date', 'market_data', ['symbol', 'date'], unique=False)
    op.create_table('stress_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Source: ecb_ciss, vix, cleveland_fci, etc.'),
    sa.Column('date', sa.Date(), nullable=False, comment='Observation date'),
    sa.Column('region', sa.String(length=10), nullable=False, comment='Region code: ea (Euro Area), de, fr, it, es, nl, be, at, fi, pt, ie, gr, us'),
    sa.Column('value', sa.Float(), nullable=False, comment='Stress index value (typically 0-1 for CISS)'),
    sa.Column('frequency', sa.String(length=10), nullable=True, comment='Data frequency: daily, weekly, monthly'),
    sa.Column('money_market', sa.Float(), nullable=True, comment='Money market component'),
    sa.Column('bond_market', sa.Float(), nullable=True, comment='Bond market component'),
    sa.Column('equity_market', sa.Float(), nullable=True, comment='Equity market component'),
    sa.Column('foreign_exchange', sa.Float(), nullable=True, comment='Foreign exchange component'),
    sa.Column('financial_intermediaries', sa.Float(), nullable=True, comment='Financial intermediaries component'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'date', 'region', name='uq_stress_index_source_date_region')
    )
    op.create_index('ix_stress_index_source_date', 'stress_indices', ['source', 'date'], unique=False)
    op.create_index(op.f('ix_stress_indices_date'), 'stress_indices', ['date'], unique=False)
    op.create_index(op.f('ix_stress_indices_source'), 'stress_indices', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_indices_source'), table_name='stress_indices')
    op.drop_index(op.f('ix_stress_indices_date'), table_name='stress_indices')
    op.drop_index('ix_stress_index_source_date', table_name='stress_indices')
    op.drop_table('stress_indices')
    op.drop_index('ix_market_data_symbol_date', table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index('ix_market_data_source', table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_index('ix_market_data_asset_type', table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
