"""Initial schema

Revision ID: 8bd1ad8b982e
Revises: 
Create Date: 2026-01-25 23:26:47.342279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bd1ad8b982e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Data source: reddit, twitter, news'),
    sa.Column('source_id', sa.String(length=100), nullable=True, comment='Original ID from source platform'),
    sa.Column('asset_class', sa.String(length=20), nullable=False, comment='Asset class: equity, crypto, forex, commodity'),
    sa.Column('content_created_at', sa.DateTime(timezone=True), nullable=False, comment='When the content was originally created'),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False, comment='When we collected this content'),
    sa.Column('title', sa.Text(), nullable=True, comment='Title (for posts/articles)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Main text content'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Source-specific metadata (score, author, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_texts_asset_class', 'raw_texts', ['asset_class'], unique=False)
    op.create_index('ix_raw_texts_content_created_at', 'raw_texts', ['content_created_at'], unique=False)
    op.create_index('ix_raw_texts_source_source_id', 'raw_texts', ['source', 'source_id'], unique=True, postgresql_where=sa.text('source_id IS NOT NULL'))
    op.create_table('regime_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of regime classification'),
    sa.Column('regime', sa.String(length=20), nullable=False, comment='Regime: risk_on, risk_off, transition'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence in classification (0-1)'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='Model version used for classification'),
    sa.Column('prob_risk_on', sa.Float(), nullable=True, comment='Probability of risk_on state'),
    sa.Column('prob_risk_off', sa.Float(), nullable=True, comment='Probability of risk_off state'),
    sa.Column('prob_transition', sa.Float(), nullable=True, comment='Probability of transition state'),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Input features used for classification'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp')
    )
    op.create_index('ix_regime_states_regime', 'regime_states', ['regime'], unique=False)
    op.create_index('ix_regime_states_timestamp', 'regime_states', ['timestamp'], unique=False)
    op.create_table('regime_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_regime', sa.String(length=20), nullable=False, comment='Previous regime state'),
    sa.Column('to_regime', sa.String(length=20), nullable=False, comment='New regime state'),
    sa.Column('transition_start', sa.DateTime(timezone=True), nullable=False, comment='When transition was first detected'),
    sa.Column('transition_end', sa.DateTime(timezone=True), nullable=True, comment='When new regime stabilized'),
    sa.Column('duration_hours', sa.Integer(), nullable=True, comment='Duration of transition in hours'),
    sa.Column('trigger_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Features that triggered the transition'),
    sa.Column('validated', sa.Boolean(), nullable=False, comment='Whether validated by subsequent price action'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transition_start')
    )
    op.create_index('ix_regime_transitions_from_to', 'regime_transitions', ['from_regime', 'to_regime'], unique=False)
    op.create_index('ix_regime_transitions_start', 'regime_transitions', ['transition_start'], unique=False)
    op.create_table('sentiment_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False, comment='Asset class: equity, crypto, forex, commodity'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Data source (NULL = all sources aggregated)'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of aggregation period'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False, comment='End of aggregation period'),
    sa.Column('granularity', sa.String(length=10), nullable=False, comment='Time granularity: hourly, daily'),
    sa.Column('mean_compound', sa.Float(), nullable=False, comment='Mean compound score for period'),
    sa.Column('std_compound', sa.Float(), nullable=True, comment='Standard deviation of compound scores'),
    sa.Column('sample_count', sa.Integer(), nullable=False, comment='Number of texts in aggregation'),
    sa.Column('positive_ratio', sa.Float(), nullable=True, comment='Ratio of positive texts'),
    sa.Column('negative_ratio', sa.Float(), nullable=True, comment='Ratio of negative texts'),
    sa.Column('sentiment_momentum', sa.Float(), nullable=True, comment='Rate of change from previous period'),
    sa.Column('sentiment_acceleration', sa.Float(), nullable=True, comment='Second derivative of sentiment'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentiment_indices_period', 'sentiment_indices', ['period_start', 'asset_class'], unique=False)
    op.create_index('ix_sentiment_indices_unique', 'sentiment_indices', ['asset_class', 'source', 'period_start', 'granularity'], unique=True)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='Model used: finbert, roberta, distilbert'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='Model version or checkpoint'),
    sa.Column('positive', sa.Float(), nullable=False, comment='Positive sentiment probability'),
    sa.Column('negative', sa.Float(), nullable=False, comment='Negative sentiment probability'),
    sa.Column('neutral', sa.Float(), nullable=False, comment='Neutral sentiment probability'),
    sa.Column('compound', sa.Float(), nullable=False, comment='Compound score (-1 to 1)'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Model confidence (max of positive/negative/neutral)'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False, comment='When this text was processed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['raw_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentiment_scores_processed_at', 'sentiment_scores', ['processed_at'], unique=False)
    op.create_index('ix_sentiment_scores_text_model', 'sentiment_scores', ['text_id', 'model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentiment_scores_text_model', table_name='sentiment_scores')
    op.drop_index('ix_sentiment_scores_processed_at', table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('ix_sentiment_indices_unique', table_name='sentiment_indices')
    op.drop_index('ix_sentiment_indices_period', table_name='sentiment_indices')
    op.drop_table('sentiment_indices')
    op.drop_index('ix_regime_transitions_start', table_name='regime_transitions')
    op.drop_index('ix_regime_transitions_from_to', table_name='regime_transitions')
    op.drop_table('regime_transitions')
    op.drop_index('ix_regime_states_timestamp', table_name='regime_states')
    op.drop_index('ix_regime_states_regime', table_name='regime_states')
    op.drop_table('regime_states')
    op.drop_index('ix_raw_texts_source_source_id', table_name='raw_texts', postgresql_where=sa.text('source_id IS NOT NULL'))
    op.drop_index('ix_raw_texts_content_created_at', table_name='raw_texts')
    op.drop_index('ix_raw_texts_asset_class', table_name='raw_texts')
    op.drop_table('raw_texts')
    # ### end Alembic commands ###
